import pygame

pack = "Assets"

TILEMAP_blockID = [
    pygame.image.load(pack + "/Tiles/Air.png"),                                                        # ID 00 = Air
    pygame.image.load(pack + "/Tiles/grass_block.png"),                                                # ID 01 = Grass block
    pygame.image.load(pack + "/Tiles/dirt_block.png"),                                                 # ID 02 = Dirt block
    pygame.image.load(pack + "/Tiles/stone_block.png"),                                                # ID 03 = Stone block
    pygame.image.load(pack + "/Tiles/Ores/Stone/ORE_STONE_coal.png"),                                  # ID 04 = Coal ore
    pygame.image.load(pack + "/Tiles/Ores/Stone/ORE_STONE_copper.png"),                                # ID 05 = Copper ore
    pygame.image.load(pack + "/Tiles/Ores/Stone/ORE_STONE_iron.png"),                                  # ID 06 = Iron ore
    pygame.image.load(pack + "/Tiles/Ores/Stone/ORE_STONE_gold.png"),                                  # ID 07 = Gold ore
    pygame.image.load(pack + "/Tiles/Ores/Stone/ORE_STONE_redstone.png"),                              # ID 08 = Redstone ore
    pygame.image.load(pack + "/Tiles/Ores/Stone/ORE_STONE_lapis.png"),                                 # ID 09 = Lapis ore
    pygame.image.load(pack + "/Tiles/Ores/Stone/ORE_STONE_diamond.png"),                               # ID 10 = Diamond ore
    pygame.image.load(pack + "/Tiles/Ores/Stone/ORE_STONE_emerald.png"),                               # ID 11 = Emerald ore
    pygame.image.load(pack + "/Tiles/deepslate.png"),                                                  # ID 12 = Deepslate
    pygame.image.load(pack + "/Tiles/Ores/Deepslate/ORE_DEEPSLATE_coal.png"),                          # ID 13 = Deepslate Coal ore
    pygame.image.load(pack + "/Tiles/Ores/Deepslate/ORE_DEEPSLATE_copper.png"),                        # ID 14 = Deepslate Copper ore
    pygame.image.load(pack + "/Tiles/Ores/Deepslate/ORE_DEEPSLATE_iron.png"),                          # ID 15 = Deepslate Iron ore
    pygame.image.load(pack + "/Tiles/Ores/Deepslate/ORE_DEEPSLATE_gold.png"),                          # ID 16 = Deepslate Gold ore
    pygame.image.load(pack + "/Tiles/Ores/Deepslate/ORE_DEEPSLATE_lapis.png"),                         # ID 17 = Deepslate Lapis ore
    pygame.image.load(pack + "/Tiles/Ores/Deepslate/ORE_DEEPSLATE_diamond.png"),                       # ID 18 = Deepslate Diamond ore
    pygame.image.load(pack + "/Tiles/Ores/Deepslate/ORE_DEEPSLATE_emerald.png"),                       # ID 19 = Deepslate Emerald ore
    pygame.image.load(pack + "/Tiles/Decor/DECOR_tallGrassDouble_BOTTOM.png"),                         # ID 20 = Double tall grass bottom
    pygame.image.load(pack + "/Tiles/Decor/DECOR_tallGrassDouble_TOP.png"),                            # ID 21 = Double tall grass top
    pygame.image.load(pack + "/Tiles/Decor/DECOR_tallGrassSingle.png"),                                # ID 22 = Single tall grass
    pygame.image.load(pack + "/Tiles/Decor/Trees/Leaves/LEAVES_oak.png"),                              # ID 23 = Oak leaves
    pygame.image.load(pack + "/Tiles/Decor/Trees/Logs/Not stripped/LOG_oakVERTICAL.png"),              # ID 24 = Oak log vertical
    pygame.image.load(pack + "/Tiles/Decor/Trees/Logs/Not stripped/LOG_oakSIDE.png"),                  # ID 25 = Oak log side
    pygame.image.load(pack + "/Tiles/Decor/Trees/Saplings/SAPLINGS_oak.png"),                          # ID 26 = Oak Sapling
    pygame.image.load(pack + "/Tiles/Decor/Trees/Saplings/SAPLINGS_oakDark.png"),                      # ID 27 = Dark oak Sapling
    pygame.image.load(pack + "/Tiles/Decor/Trees/Saplings/SAPLINGS_spruce.png"),                       # ID 28 = Spruce Sapling
    pygame.image.load(pack + "/Tiles/Decor/Trees/Saplings/SAPLINGS_acacia.png"),                       # ID 29 = Acacia Sapling
    pygame.image.load(pack + "/Tiles/Decor/Trees/Saplings/SAPLINGS_birch.png"),                        # ID 30 = Birch Sapling
    pygame.image.load(pack + "/Tiles/Decor/Trees/Saplings/SAPLINGS_jungle.png"),                       # ID 31 = Jungle Sapling
    # ------------------------------------------------------------------------------------------------------------------------------------- ITEM START: 32 ----------------
    pygame.image.load(pack + "/Items/coal.png"),                                                       # ID 32 = Coal
    pygame.image.load(pack + "/Items/copper_ingot.png"),                                               # ID 33 = Copper Ingot
    pygame.image.load(pack + "/Items/iron_ingot.png"),                                                 # ID 34 = Iron ingot
    pygame.image.load(pack + "/Items/gold_ingot.png"),                                                 # ID 35 = Gold ingot
    pygame.image.load(pack + "/Items/redstone.png"),                                                   # ID 36 = Redstone dust
    pygame.image.load(pack + "/Items/lapis_lazuli.png"),                                               # ID 37 = Lapis lazuli
    pygame.image.load(pack + "/Items/diamond.png"),                                                    # ID 38 = Diamond
    pygame.image.load(pack + "/Items/netherite_ingot.png"),                                            # ID 39 = Netherite ingot
    pygame.image.load(pack + "/Items/raw_copper.png"),                                                 # ID 40 = Raw copper
    pygame.image.load(pack + "/Items/raw_iron.png"),                                                   # ID 41 = Raw iron
    pygame.image.load(pack + "/Items/raw_gold.png"),                                                   # ID 42 = Raw gold
    pygame.image.load(pack + "/Items/netherite_scrap.png"),                                            # ID 43 = Netherite scrap
    pygame.image.load(pack + "/Items/leather_helmet.png"),                                             # ID 44 = Leather helmet
    pygame.image.load(pack + "/Items/leather_chestplate.png"),                                         # ID 45 = Leather chesplate
    pygame.image.load(pack + "/Items/leather_leggings.png"),                                           # ID 46 = Leather leggings
    pygame.image.load(pack + "/Items/leather_boots.png"),                                              # ID 47 = Leather boots
    pygame.image.load(pack + "/Items/shield.png"),                                                     # ID 48 = Shield
]

#blockID = AssetID
#
#TILEMAP_blockID = blockID
#showID = TILEMAP_blockID

TILEMAP_blockID_itemStart = 32

TILEMAP_blockID_NAMES = [
    "Air",                                                                                             # ID 00 = Air
    "Grass block",                                                                                     # ID 01 = Grass block
    "Dirt block",                                                                                      # ID 02 = Dirt block
    "Stone block",                                                                                     # ID 03 = Stone block
    "Coal ore",                                                                                        # ID 04 = Coal ore
    "Copper ore",                                                                                      # ID 05 = Copper ore
    "Iron ore",                                                                                        # ID 06 = Iron ore
    "Gold ore",                                                                                        # ID 07 = Gold ore
    "Redstone ore",                                                                                    # ID 08 = Redstone ore 
    "Lapis ore",                                                                                       # ID 09 = Lapis ore
    "Diamond ore",                                                                                     # ID 10 = Diamond ore
    "Emerald ore",                                                                                     # ID 11 = Emerald ore
    "Deepslate",                                                                                       # ID 12 = Deepslate
    "Deepslate Coal ore",                                                                              # ID 13 = Deepslate Coal ore
    "Deepslate Copper ore",                                                                            # ID 14 = Deepslate Copper ore
    "Deepslate Iron ore",                                                                              # ID 15 = Deepslate Iron ore
    "Deepslate Gold ore",                                                                              # ID 16 = Deepslate Gold ore
    "Deepslate Lapis ore",                                                                             # ID 17 = Deepslate Lapis ore
    "Deepslate Diamond ore",                                                                           # ID 18 = Deepslate Diamond ore
    "Deepslate Emerald ore",                                                                           # ID 19 = Deepslate Emerald ore
    "Double tall grass bottom",                                                                        # ID 20 = Double tall grass bottom
    "Double tall grass top",                                                                           # ID 21 = Double tall grass top
    "Single tall grass",                                                                               # ID 22 = Single tall grass
    "Oak leaves",                                                                                      # ID 23 = Oak leaves
    "Oak log vertical",                                                                                # ID 24 = Oak log vertical
    "Oak log side",                                                                                    # ID 25 = Oak log side
    "Oak Sapling",                                                                                     # ID 26 = Oak Sapling
    "Dark oak Sapling",                                                                                # ID 27 = Dark oak Sapling
    "Spruce Sapling",                                                                                  # ID 28 = Spruce Sapling
    "Acacia Sapling",                                                                                  # ID 29 = Acacia Sapling
    "Birch Sapling",                                                                                   # ID 30 = Birch Sapling
    "Jungle Sapling",                                                                                  # ID 31 = Jungle Sapling
    "Coal",                                                                                            # ID 32 = Coal
    "Copper Ingot",                                                                                    # ID 33 = Copper Ingot
    "Iron ingot",                                                                                      # ID 34 = Iron ingot
    "Gold ingot",                                                                                      # ID 35 = Gold ingot
    "Redstone dust",                                                                                   # ID 36 = Redstone dust
    "Lapis lazuli",                                                                                    # ID 37 = Lapis lazuli
    "Diamond",                                                                                         # ID 38 = Diamond
    "Netherite ingot",                                                                                 # ID 39 = Netherite ingot
    "Raw copper",                                                                                      # ID 40 = Raw copper
    "Raw iron",                                                                                        # ID 41 = Raw iron
    "Raw gold",                                                                                        # ID 42 = Raw gold
    "Netherite scrap",                                                                                 # ID 43 = Netherite scrap
    "Leather helmet",                                                                                  # ID 44 = Leather helmet
    "Leather chesplate",                                                                               # ID 45 = Leather chesplate
    "Leather leggings",                                                                                # ID 46 = Leather leggings
    "Leather boots",                                                                                   # ID 47 = Leather boots
]

INVENTORY_ID = [
 pygame.image.load(pack + "/GUIs/INVENTORY_survival.png"),                                             # ID 00 = Survival inventory
 pygame.image.load(pack + "/GUIs/INVENTORY_yesno.png"),                                                # ID 01 = Yes / No option
 pygame.image.load(pack + "/GUIs/Creative/CREATIVE_inventory.png"),                                    # ID 02 = Creative inventory
 pygame.image.load(pack + "/GUIs/Creative/CREATIVE_invSearch.png"),                                    # ID 03 = Creative search
 pygame.image.load(pack + "/GUIs/Creative/CREATIVE_invTabs.png"),                                      # ID 04 = Creative tab menu 
 pygame.image.load(pack + "/GUIs/Creative/CREATIVE_tabsUP_SEL.png"),                                   # ID 05 = Tabs - Up Selected
 pygame.image.load(pack + "/GUIs/Creative/CREATIVE_tabsUP_DESEL.png"),                                 # ID 06 = Tabs - Up Deselected
 pygame.image.load(pack + "/GUIs/Creative/CREATIVE_tabsDOWN_SEL.png"),                                 # ID 07 = Tabs - Down Selected
 pygame.image.load(pack + "/GUIs/Creative/CREATIVE_tabsDOWN_DESEL.png"),                               # ID 08 = Tabs - Down Deselected
 pygame.image.load(pack + "/GUIs/INVENTORY_hotbar.png"),                                               # ID 09 = Hotbar
 pygame.image.load(pack + "/GUIs/INVENTORY_hotbarOffHand.png"),                                        # ID 10 = Hotbar offhand
 pygame.image.load(pack + "/GUIs/INVENTORY_hotbarSelected.png"),                                       # ID 11 = Hotbar selected
 pygame.image.load(pack + "/GUIs/INVENTORY_tileSelected.png"),                                         # ID 12 = Invenory tile selected
]

INVENTORY_ID_creative_Inventory_SlotPos = [
    (74, 7),                                                                                           # ID 00 = Player
    (55, 7),                                                                                           # ID 01 = Helmet
    (55,   34),                                                                                        # ID 02 = Chestplate
    (109,   7),                                                                                        # ID 03 = Leggings
    (109,  34),                                                                                        # ID 04 = Boots
    (36,   21),                                                                                        # ID 05 = Offhand
    (10,   55),                                                                                        # ID 06 = Slot num 1, 1
    (28,   55),                                                                                        # ID 07 = Slot num 1, 2
    (46,   55),                                                                                        # ID 08 = Slot num 1, 3
    (64,   55),                                                                                        # ID 09 = Slot num 1, 4
    (82,   55),                                                                                        # ID 10 = Slot num 1, 5
    (100,  55),                                                                                        # ID 11 = Slot num 1, 6
    (118,  55),                                                                                        # ID 12 = Slot num 1, 7
    (136,  55),                                                                                        # ID 13 = Slot num 1, 8
    (154,  55),                                                                                        # ID 14 = Slot num 1, 9
    (10,   73),                                                                                        # ID 15 = Slot num 2, 1
    (28,   73),                                                                                        # ID 16 = Slot num 2, 2
    (46,   73),                                                                                        # ID 17 = Slot num 2, 3
    (64,   73),                                                                                        # ID 18 = Slot num 2, 4
    (82,   73),                                                                                        # ID 19 = Slot num 2, 5
    (100,  73),                                                                                        # ID 20 = Slot num 2, 6
    (118,  73),                                                                                        # ID 21 = Slot num 2, 7
    (136,  73),                                                                                        # ID 22 = Slot num 2, 8
    (154,  73),                                                                                        # ID 23 = Slot num 2, 9
    (10,   91),                                                                                        # ID 24 = Slot num 3, 1
    (28,   91),                                                                                        # ID 25 = Slot num 3, 2
    (46,   91),                                                                                        # ID 26 = Slot num 3, 3
    (64,   91),                                                                                        # ID 27 = Slot num 3, 4
    (82,   91),                                                                                        # ID 28 = Slot num 3, 5
    (100,  91),                                                                                        # ID 29 = Slot num 3, 6
    (118,  91),                                                                                        # ID 30 = Slot num 3, 7
    (136,  91),                                                                                        # ID 31 = Slot num 3, 8
    (154,  91),                                                                                        # ID 32 = Slot num 3, 9
    (10,  113),                                                                                        # ID 33 = Hotbar slot num 1
    (28,  113),                                                                                        # ID 34 = Hotbar slot num 2
    (46,  113),                                                                                        # ID 35 = Hotbar slot num 3
    (64,  113),                                                                                        # ID 36 = Hotbar slot num 4
    (82,  113),                                                                                        # ID 37 = Hotbar slot num 5
    (100, 113),                                                                                        # ID 38 = Hotbar slot num 6
    (118, 113),                                                                                        # ID 39 = Hotbar slot num 7
    (136, 113),                                                                                        # ID 40 = Hotbar slot num 8
    (154, 113),                                                                                        # ID 41 = Hotbar slot num 9
]

INVENTORY_ID_creative_Inventory_SlotPos = [
    (74, 7),                                                                                           # ID 00 = Player
    (55, 7),                                                                                           # ID 01 = Helmet
    (55,   34),                                                                                        # ID 02 = Chestplate
    (109,   7),                                                                                        # ID 03 = Leggings
    (109,  34),                                                                                        # ID 04 = Boots
    (36,   21),                                                                                        # ID 05 = Offhand
    (10,   55),                                                                                        # ID 06 = Slot num 1, 1
    (28,   55),                                                                                        # ID 07 = Slot num 1, 2
    (46,   55),                                                                                        # ID 08 = Slot num 1, 3
    (64,   55),                                                                                        # ID 09 = Slot num 1, 4
    (82,   55),                                                                                        # ID 10 = Slot num 1, 5
    (100,  55),                                                                                        # ID 11 = Slot num 1, 6
    (118,  55),                                                                                        # ID 12 = Slot num 1, 7
    (136,  55),                                                                                        # ID 13 = Slot num 1, 8
    (154,  55),                                                                                        # ID 14 = Slot num 1, 9
    (10,   73),                                                                                        # ID 15 = Slot num 2, 1
    (28,   73),                                                                                        # ID 16 = Slot num 2, 2
    (46,   73),                                                                                        # ID 17 = Slot num 2, 3
    (64,   73),                                                                                        # ID 18 = Slot num 2, 4
    (82,   73),                                                                                        # ID 19 = Slot num 2, 5
    (100,  73),                                                                                        # ID 20 = Slot num 2, 6
    (118,  73),                                                                                        # ID 21 = Slot num 2, 7
    (136,  73),                                                                                        # ID 22 = Slot num 2, 8
    (154,  73),                                                                                        # ID 23 = Slot num 2, 9
    (10,   91),                                                                                        # ID 24 = Slot num 3, 1
    (28,   91),                                                                                        # ID 25 = Slot num 3, 2
    (46,   91),                                                                                        # ID 26 = Slot num 3, 3
    (64,   91),                                                                                        # ID 27 = Slot num 3, 4
    (82,   91),                                                                                        # ID 28 = Slot num 3, 5
    (100,  91),                                                                                        # ID 29 = Slot num 3, 6
    (118,  91),                                                                                        # ID 30 = Slot num 3, 7
    (136,  91),                                                                                        # ID 31 = Slot num 3, 8
    (154,  91),                                                                                        # ID 32 = Slot num 3, 9
    (10,  113),                                                                                        # ID 33 = Hotbar slot num 1
    (28,  113),                                                                                        # ID 34 = Hotbar slot num 2
    (46,  113),                                                                                        # ID 35 = Hotbar slot num 3
    (64,  113),                                                                                        # ID 36 = Hotbar slot num 4
    (82,  113),                                                                                        # ID 37 = Hotbar slot num 5
    (100, 113),                                                                                        # ID 38 = Hotbar slot num 6
    (118, 113),                                                                                        # ID 39 = Hotbar slot num 7
    (136, 113),                                                                                        # ID 40 = Hotbar slot num 8
    (154, 113),                                                                                        # ID 41 = Hotbar slot num 9
    ]

INVENTORY_current = [
    00,                                                                                                # ID 00 = Player
    44,                                                                                                # ID 01 = Helmet
    45,                                                                                                # ID 02 = Chestplate
    46,                                                                                                # ID 03 = Leggings
    47,                                                                                                # ID 04 = Boots
    00,                                                                                                # ID 05 = Offhand
     1,                                                                                                # ID 06 = Slot num 1, 1
    00,                                                                                                # ID 07 = Slot num 1, 2
    00,                                                                                                # ID 08 = Slot num 1, 3
    00,                                                                                                # ID 09 = Slot num 1, 4
    00,                                                                                                # ID 10 = Slot num 1, 5
    00,                                                                                                # ID 11 = Slot num 1, 6
    00,                                                                                                # ID 12 = Slot num 1, 7
    00,                                                                                                # ID 13 = Slot num 1, 8
    00,                                                                                                # ID 14 = Slot num 1, 9
    00,                                                                                                # ID 15 = Slot num 2, 1
     1,                                                                                                # ID 16 = Slot num 2, 2
    00,                                                                                                # ID 17 = Slot num 2, 3
    00,                                                                                                # ID 18 = Slot num 2, 4
    00,                                                                                                # ID 19 = Slot num 2, 5
    00,                                                                                                # ID 20 = Slot num 2, 6
    00,                                                                                                # ID 21 = Slot num 2, 7
    00,                                                                                                # ID 22 = Slot num 2, 8
    00,                                                                                                # ID 23 = Slot num 2, 9
    00,                                                                                                # ID 24 = Slot num 3, 1
    00,                                                                                                # ID 25 = Slot num 3, 2
     1,                                                                                                # ID 26 = Slot num 3, 3
    00,                                                                                                # ID 27 = Slot num 3, 4
    00,                                                                                                # ID 28 = Slot num 3, 5
    00,                                                                                                # ID 29 = Slot num 3, 6
    00,                                                                                                # ID 30 = Slot num 3, 7
    00,                                                                                                # ID 31 = Slot num 3, 8
    00,                                                                                                # ID 32 = Slot num 3, 9
     1,                                                                                                # ID 33 = Hotbar slot num 1
     2,                                                                                                # ID 34 = Hotbar slot num 2
     3,                                                                                                # ID 35 = Hotbar slot num 3
     4,                                                                                                # ID 36 = Hotbar slot num 4
    00,                                                                                                # ID 37 = Hotbar slot num 5
    20,                                                                                                # ID 38 = Hotbar slot num 6
    21,                                                                                                # ID 39 = Hotbar slot num 7
    22,                                                                                                # ID 40 = Hotbar slot num 8
    26,                                                                                                # ID 41 = Hotbar slot num 9
]

MOUSE_breakCursor = [
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s0.png"),                      # ID 00 = Block cursor
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s1.png"),                      # ID 01 = Block destroy stage 1
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s2.png"),                      # ID 02 = Block destroy stage 2
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s3.png"),                      # ID 03 = Block destroy stage 3
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s4.png"),                      # ID 04 = Block destroy stage 4
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s5.png"),                      # ID 05 = Block destroy stage 5
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s6.png"),                      # ID 06 = Block destroy stage 6
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s7.png"),                      # ID 07 = Block destroy stage 7
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s8.png"),                      # ID 08 = Block destroy stage 8
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s9.png"),                      # ID 09 = Block destroy stage 9
    pygame.image.load(pack + "Assets/Tiles/Block destroy stages/DESTROY_s10.png"),                     # ID 10 = Block destroy stage 10
]
F3_STARTPOS = 20
scrollOriginal = 0

pygame.display.set_icon(pygame.image.load(pack + "/Tiles/Tables/TABLE_crafting.png"))

DEBUG = [True, False, False]

COLOURS_black = (0, 0, 0)
COLOURS_white = (255, 255, 255)
COLOURS_green = (0, 255, 0)
COLOURS_red = (255, 0, 0)
COLOURS_skyBlue = (28, 141, 227)

PLAYER_x = 10
PLAYER_y = 10

BLOCK_size = 64
BLOCK_sizeOriginal = 16

length2 = 0
length2command = "", COLOURS_white, 0, 0

HOTBAR_selectedSlot = 0
HOTBAR_TileSelected = -1